### ISSUE TITLE
Backspace key not working

### ISSUE THREAD

**Issue by Esteban-Rocha** [Jasonlhy/VSCode-Hungry-Delete#1]
Hi! it seem latest VS code update may have broken something, I cannot seem to use the backspace as long as the extension is activated.

Version 1.14.2
Commit cb82febafda0c8c199b9201ad274e25d9a76874e
Date 2017-07-19T23:26:08.116Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0

**Comment by Jasonlhy** [comment]
Do you still encounter the issue? and what is your operation system? I updated the version of vscode to 1.14.2 and it works fine under windows 7. Sometimes

**Comment by Jasonlhy** [comment]
I remove my custom key binding and tried again. It also works fine. Remember to put `"hungryDelete.enableSmartBackspace": true` in the setting file :)
