### ISSUE TITLE
Visual Studio version

### ISSUE THREAD

**Issue by ghost1372** [Jasonlhy/VSCode-Hungry-Delete#10]
hi tnx for this great ext
i need this ext for visual studio can you please create it for vs 2019?

**Comment by craig-ten-uh** [comment]
For reference for people who come to this issue, there is a similar extension made by someone else for VS 2022.

[https://marketplace.visualstudio.com/items?itemName=iWenPeng.SpaceAsTab](https://marketplace.visualstudio.com/items?itemName=iWenPeng.SpaceAsTab)
