### ISSUE TITLE
support using delete as well

### ISSUE THREAD

**Issue by ctf0** [Jasonlhy/VSCode-Hungry-Delete#11]
atm we can use `backspace` which removes the indentation space to the left, but is it possible to also support using `delete` to remove the ones from the right ?

its the same behavior as now but in reverse.

**Comment by Jasonlhy** [comment]
I believe what you are looking for is "Delete world right" in vscode ? It acts like `ctrl+k` in emacs, it is `ctrl+k` in Mac and `ctrl+delete` in Windows

**Comment by ctf0** [comment]
not exactly because lets say we have something like
```
start|

    end
```
`|` is the cursor & u started using `Delete world right` , now you need to use it at least 2 times to get to the word `end`, but with the help or an extension, we could only use it once
