### ISSUE TITLE
Delete () [] {} problem

### ISSUE THREAD

**Issue by tiansin** [Jasonlhy/VSCode-Hungry-Delete#2]
When the cursor is placed in the middle of the deletion will be deleted (), but I installed this plug-in can only delete the left

**Comment by tiansin** [comment]
![1](https://user-images.githubusercontent.com/4232281/32232544-3de4d680-be93-11e7-8293-96a4c9bbb2a1.png)

I found that this plugin will have the chance to enter the death cycle, because I have appeared several times, in the preparation of html code in the case, and this code may be related

**Comment by Jasonlhy** [comment]
Thanks for your feedback, but can you provide the scenario so I can reproduce the bug? Do you means (`|`) where `|` is the cursor?

**Comment by tiansin** [comment]
Thank you for your answer, that is the case.

**Comment by tiansin** [comment]
Sorry that English is not good and may not be understood

**Comment by Jasonlhy** [comment]
I can't reproduce the issue on my computer. Can you provide me the environment and the version of vscode you are using?

**Comment by Jasonlhy** [comment]
Thanks for the pull request, being quite busy in recent weeks. After I do more testings, I will update it on the market.

**Comment by tiansin** [comment]
Thank you for your update!!
