### ISSUE TITLE
extension breaks backspace on WSL

### ISSUE THREAD

**Issue by ooliver1** [Jasonlhy/VSCode-Hungry-Delete#33]
Issue Type: <b>Bug</b>

(i no longer use this extension so not much use)
today i started to migrate to WSL and found backspace was sketchy when indented
i did an extension bisect and found this ext to be tne issue

i can provide more info if you cannot repro

Extension version: 1.6.0
VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Connection to 'wsl+ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU 5405U @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.24GB free)|
|Process Argv|--crash-reporter-id a74f7f50-3f88-445b-b61a-6be13154f614|
|Screen Reader|no|
|VM|0%|

Connection to 'wsl+ubuntu' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
vscaac:30438847
pynewfile477:30463512

```

</details>

**Comment by Jasonlhy** [comment]
I can't reproduce, can you still reproduce with the latest version of VSCode

**Comment by ooliver1** [comment]
i no longer use WSL nor do i use this extension anymore, sorry
